id: I0401DDF5
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:24:52.820288
last_modified: 2023-02-10 00:24:52.820389
source_metadata:
  title: 'Asaṅga: Abhidharmasamuccaya'
  language: zh
bases:
  13EA:
    base_file: 13EA.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
